ifneq (,$(filter coap_% mqtt_%,$(USEMODULE)))
  # Include packages that pull up and auto-init the link layer.
  # NOTE: 6LoWPAN will be included if IEEE802.15.4 devices are present
  USEMODULE += gnrc_netdev_default
  USEMODULE += auto_init_gnrc_netif
  # Specify the mandatory networking modules for IPv6 and UDP
  USEMODULE += gnrc_ipv6_default
  # Additional networking modules that can be dropped if not needed
  USEMODULE += gnrc_icmpv6_echo
  USEMODULE += gnrc_sock_udp
endif

ifneq (,$(filter coap_%,$(USEMODULE)))
  USEMODULE += gcoap
endif

ifneq (,$(filter mqtt_%,$(USEMODULE)))
  USEMODULE += emcute
endif
